apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs1
    app.kubernetes.io/part-of: my-application-1
  name: nodejs1
  namespace: eyuen
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs1
    weight: 100
status: {}
