apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs1
    app.kubernetes.io/part-of: my-application-1
  name: nodejs1
  namespace: eyuen
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs1
status:
  loadBalancer: {}
